---
title: "Memory Usage"
output: rmarkdown::html_vignette
self_contained: true
vignette: >
  %\VignetteIndexEntry{memory}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```

```{r setup}
library(dplyr)
library(ggplot2)
library(glue)
library(readr)
# library(reneeTools)
devtools::load_all()
```

Dataset from: <https://portal.gdc.cancer.gov/projects/TCGA-LIHC>

```{r data}
counts <- read_tsv("~/Downloads/LIHC_HTseqCounts.txt") %>%
  rename(gene_id = Gene)
metadat <- read_tsv("~/Downloads/LIHC_PatientData.txt") %>%
  select(-sample_id) %>%
  rename(sample_id = barcode)
renee_ds <- create_reneeDataSet_from_dataframes(metadat, counts) %>%
  calc_cpm() %>%
  filter_counts(
    sample_names_column = "sample_id",
    gene_names_column = "gene_id",
    group_column = "treatments_radiation_treatment_type",
    label_column = "sample",
    columns_to_include = c("gene_id", metadat %>% pull("sample_id")),
    make_plots = FALSE
  )
```


```{r subset}
subset_data <- function(renee_ds, nsamples) {
  renee_ds_subset <- renee_ds
  renee_ds_subset@sample_meta <- renee_ds@sample_meta %>% slice_sample(n = nsamples)
  for (count_type in names(renee_ds@counts)) {
    renee_ds_subset@counts[[count_type]] <- renee_ds@counts[[count_type]] %>%
      select(gene_id, all_of(renee_ds_subset@sample_meta$sample_id))
  }
  return(renee_ds_subset)
}

subset_mem <- lapply(c(10, 50, 100, 200, nrow(renee_ds@sample_meta)), function(nsamples) {
  renee_ds_subset <- subset_data(renee_ds, nsamples)
  return(tibble(
    n_samples = nsamples,
    object_size = lobstr::obj_size(renee_ds_subset)
  ))
}) %>%
  bind_rows()
```

```{r single_cell}
to_bytes <- function(x, unit, base = 1024) {
  bytes_units <- list(
    K = 1,
    M = 2,
    G = 3,
    T = 4
  )
  return(x * (base^bytes_units[[unit]]))
}
sc_dat <- tibble::tribble(
  ~"project", ~"n_cells", ~"n_samples", ~"n_genes", ~"object_size_GB",
  "CCBR1329/CCBR1243", 64642, 10, 26359, 9.35,
  "CCBR1297", 9991, 2, 20989, 1.78,
  "CCBR1035", 170789, 19, 32100, 31.54,
  "CCBR1203", 208169, 35, 30858, 37.38
) %>%
  mutate(
    object_size = to_bytes(object_size_GB, "G", base = 1000),
    dataset_type = "single-cell (Seurat)"
  )
```


```{r plot_memory}
# what is the resource spec of default NIDAP allocation?
palette_name <- "Set2"
subset_mem %>%
  ggplot(aes(n_samples, object_size, color = "")) +
  geom_point() +
  geom_line(linewidth = 0.3) +
  scale_y_continuous(labels = scales::label_bytes(units = "GB", accuracy = 0.1)) +
  scale_color_manual(values = RColorBrewer::brewer.pal(3, palette_name)[[1]]) +
  labs(
    title = "Memory usage of S7 object",
    x = "Number of samples",
    y = "Memory usage",
    caption = glue(
      "The object contains sample metadata and count data as raw, CPM-transformed, and filtered counts.\n",
      "Each dataset has the same number of genes: ",
      format(length(renee_ds@counts$raw$gene_id), big.mark = ",")
    )
  ) +
  theme_bw() +
  theme(legend.position = "none")
```

```{r plot_memory_comp}
dat_comp <- bind_rows(
  subset_mem %>% mutate(dataset_type = "bulk (S7)", object_size = as.double(object_size)),
  sc_dat
)
dat_comp %>%
  ggplot(aes(n_samples, object_size, colour = dataset_type)) +
  geom_point() +
  geom_line(linewidth = 0.3) +
  scale_y_continuous(labels = scales::label_bytes(units = "GB", accuracy = 0.1)) +
  scale_color_brewer(palette = palette_name) +
  guides(colour = guide_legend(
    title = "",
    position = "top",
    reverse = TRUE,
    theme = theme(legend.text.position = "top")
  )) +
  labs(title = "Memory usage of bulk & single-cell RNA-seq objects", x = "Number of samples", y = "Memory usage") +
  theme_bw()
```
