#' RSEM genes results file
#'
#' @format ## `wt_s1_genes`
#' A data frame with 10 rows and 17 columns generated by RSEM.
#'
#' @source Generated by running RENEE v2.5.3 on the
#' [test dataset](https://github.com/CCBR/RENEE/tree/e08f7db6c6e638cfd330caa182f64665d2ef37fa/.tests)
#' and subsetting the genes results file `DEG_ALL/WT_S1.RSEM.genes.results` to the first 10 rows.
"wt_s1_genes"
