#' RSEM expected gene counts
#'
#' @format ## `gene_counts`
#' A data frame with columns 'gene_id', 'GeneName', and a column for each sample's expected count.
#'
#' @source Generated by running RENEE v2.5.8 on the
#' [test dataset](https://github.com/CCBR/RENEE/tree/e08f7db6c6e638cfd330caa182f64665d2ef37fa/.tests)
"gene_counts"
